"""
Trust Attestation API routes.
Exposes verifiable claim cards generated by the Trust Agent.

Endpoints:
  GET  /v1/trust/attestations  - Get user's attestation cards
  POST /v1/trust/refresh       - Manually trigger Trust Agent re-evaluation
"""
from flask import Blueprint, request, jsonify, current_app, g

from src.api.auth.decorators import require_auth
from src.agents.trust_agent import generate_attestations
import logging

logger = logging.getLogger("looma.trust_routes")

trust_bp = Blueprint("trust", __name__)


def _get_db():
    return current_app._db


@trust_bp.route("/attestations", methods=["GET"])
@require_auth
def get_attestations():
    """Get all trust attestation cards for the current user."""
    db = _get_db()
    attestations = db.get_trust_attestations(g.user_id)
    return jsonify(attestations=attestations, total=len(attestations))


@trust_bp.route("/refresh", methods=["POST"])
@require_auth
def refresh_attestations():
    """Manually trigger Trust Agent re-evaluation for the current user."""
    db = _get_db()
    try:
        results = generate_attestations(g.user_id, db)
        return jsonify(
            message="attestations refreshed",
            attestations=results,
            total=len(results),
        )
    except Exception as e:
        return jsonify(error="server_error", message=str(e)), 500